### ISSUE TITLE
your preprocessed data link is broken

### ISSUE THREAD

**Issue by nightandweather** [raghavian/cFlow#1]
Thank you for sharing your project!

I tried to follow your paper, but I think the data preprocessed link is broken.

Can you check it out?

Thank you

**Comment by raghavian** [comment]
Hey, the repository is still being updated. We expect it to be fully up and running in about a week's time. Thanks for pointing out.

**Comment by ToBeNormal** [comment]
@raghavian Hi，the downloaded dataset file is broken. Can you check it out？ Thanks a lot！
